# Generated by Django — hand-aligned with sender.models

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_network_credential"),
        ("editor", "0008_post_slug_redirect"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2048)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_links",
                        to="core.network",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender_links",
                        to="editor.post",
                    ),
                ),
            ],
            options={
                "db_table": "sender_postlink",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="postlink",
            constraint=models.UniqueConstraint(
                fields=("post", "network"),
                name="sender_postlink_post_network_uniq",
            ),
        ),
    ]
