# Generated by Django 6.0.1 on 2026-02-18 09:21

import editor.models.post
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_post_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postseries',
            options={'ordering': ['series', 'order_position']},
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(upload_to='img/post/2026/02/18', validators=[editor.models.post.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready_to_publish', 'Ready to publish'), ('published', 'Published')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='postgalleryimage',
            name='image',
            field=models.ImageField(upload_to='img/post/gallery/%Y/%m/%d', validators=[editor.models.post.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='postgalleryimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order within this gallery (lower first).'),
        ),
        migrations.AlterUniqueTogether(
            name='postseries',
            unique_together={('series', 'order_position')},
        ),
    ]
