# Generated by Django 6.0.2 on 2026-04-17 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0007_alter_postseries_options_alter_post_cover_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostSlugRedirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_slug", models.SlugField(max_length=250, unique=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slug_redirects",
                        to="editor.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post slug redirect (301)",
                "verbose_name_plural": "Post slug redirects (301)",
                "db_table": "editor_postslugredirect",
            },
        ),
    ]
