# Generated by Django 6.0.1 on 2026-05-15 15:38

import editor.models.post
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0008_post_slug_redirect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(upload_to='img/post/2026/05/15', validators=[editor.models.post.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='postgalleryimage',
            name='gallery_key',
            field=models.PositiveIntegerField(default=1, help_text='Gallery number. Use [gallery:1] in body for this gallery, [gallery:2] for the next, etc.'),
        ),
        migrations.AlterField(
            model_name='postseries',
            name='order_position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Order position in series'),
        ),
    ]
