# Generated by Django 6.0.1 on 2026-05-15 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_copy_blog_tables_to_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='team.person'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='team.person'),
        ),
    ]
