# Generated by Django 6.0.1 on 2026-05-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_seed_site_publications'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sitepublication',
            new_name='blog_sitepu_publish_3e0eea_idx',
            old_name='blog_sitepub_pubat_idx',
        ),
    ]
