# Generated by Django 5.2.2 on 2025-11-11 20:53

import blog.models.post
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial_squashed_0003_alter_post_cover_description_alter_post_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(upload_to='img/post/2025/11/11', validators=[blog.models.post.validate_image_extension]),
        ),
    ]
