# Generated by Django 5.2.2 on 2025-11-26 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_views_alter_post_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='series',
        ),
        migrations.CreateModel(
            name='PostSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_position', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Order position in series')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_series', to='blog.post')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_posts', to='blog.series')),
            ],
            options={
                'ordering': ['series', 'order_position'],
                'unique_together': {('series', 'order_position')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='blog_series', through='blog.PostSeries', to='blog.series'),
        ),
    ]
