# Generated by Django 5.2.2 on 2025-06-27 14:15

import blog.models.post
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_account_id_alter_accountgroup_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(upload_to='img/post/2025/06/27', validators=[blog.models.post.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image_credits',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
