# Generated by Django 3.1.7 on 2021-04-25 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210425_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.account'),
        ),
        migrations.AlterField(
            model_name='person',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.skill'),
        ),
    ]
