# Generated by Django 3.1.7 on 2021-04-25 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210425_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='account',
        ),
        migrations.RemoveField(
            model_name='person',
            name='skill',
        ),
        migrations.AddField(
            model_name='skill',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.person'),
        ),
    ]
