# Generated by Django 3.1.7 on 2021-04-25 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210425_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.person'),
        ),
    ]
