# Generated by Django 3.1.7 on 2021-07-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210724_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
