# Generated by Django 3.1.7 on 2022-06-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20220621_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='icon',
            field=models.FileField(upload_to='img/template/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(upload_to='img/post/2022/06/23'),
        ),
    ]
